### ISSUE TITLE
Izumi Chest Smother & Worm Re-Infestation Scenes Missing?

### ISSUE THREAD

**Issue by Nightfire666** [Kitteh6660/Corruption-of-Champions-Mod#1011]
I've had trouble triggering two separate scenes for a long time. Izumi (the Oni in the High Mountains cave) doesn't do her smother attack (not the choking attack, but her boob smother attack with the unique loss scene) regardless of genitals, clothing or stats. It works with 1.0.2_1.3.25 and below, but no longer appears starting in 1.0.2_1.4. The attack used to trigger as soon as you get her down to 25% health, leading to a Struggle/Do Nothing choice, but now she just does regular attacks.

The second issue is the worms and their night re-infestation scene, which still occurs in CoC_0.9.2_mod_1.1.13. Once you go to version 0.9.4C_mod_1.2.18 or higher (right up to the current version of 1.0.2_mod_1.4.11), it disappears. It should have a chance of occurring every night after being cured of worms, but despite waiting for over a hundred nights in a row across multiple versions, it never happens.

As for possible solutions, well, I'm not sure. I have next to no experience with coding, and the change log for the Izumi scene's first disappearance (CoC_1.0.2_mod_1.4) mentions two vague possibilities. Under Changes/Tweaks: "All used unknown flags have been renamed for readability in code. " Under Bug Fixes, there's the far more vague "and more fixes that aren't listed", so it could be a matter of one bug fix causing another problem, but otherwise, I haven't the foggiest idea.

With the worm scene that disappeared, I think it relates to a change made in 0.9.4_mod_1.2.1. Taken from that change log: "Moved worms.as from includes to Scenes/Areas/Mountain folder. This is another step towards gradual elimination of includes. The copyright license is retained.". Looking at the source file for CoC_0.9.2_mod_1.1.13 (the last time the scene worked), my best guess is that "Worms.as" was renamed to "WormsScene", as originally, the only worm-related file in Scenes/Areas/Mountain was "WormMass.as", and that change in title caused the scene disappearance, but I can't be certain. I could only compare 0.9.2_mod_1.1.13 to 0.9.4_mod_1.2.18's source file as the actual 0.9.4_mod_1.2.1 isn't on the Releases page.

Hopefully those scenes can be restored. As I said, I'm no coder, but I hope this can help.

**Comment by Kitteh6660** [comment]
Looked into the code. Turns out that the check for tit smother involves checking if she has the status effect, which she doesn't have. The piece of code only fires if she already has the status effect, which she doesn't. Thus causing it to never fire.

And the checks for worms infestation eligibility appear so messy! According to the code, there's 5% chance of infestation. I'll simplify that one. The following will make it so worms can't infest you:

* Lacking a cock.
* Sleeping in your cabin since the door will be locked.
* Sleeping with Arian or Ember, starting in 1.4.12.
* Having Helia, Jojo or Kid A guard your camp.

Both of the issues will be resolved hopefully in 1.4.12.
