### ISSUE TITLE
Inconsistency with Kelt between the wiki and the actual modded game.

### ISSUE THREAD

**Issue by CrimsonTheMad** [Kitteh6660/Corruption-of-Champions-Mod#1072]
When I first turned the tables on Kelt, triggering the rather rough punishment of the centaur, I grew a bit more curious as to whether or not there were special scenes for special species types. To my surprise, I found corrupt Kelt on the wiki, right (Spoilers below on how you are supposed to be able to obtain corrupt Kelt). 

On the site page for the corrupt Kelt/Kelly, ([Link to the page here.](http://coc-revamp-mod.wikia.com/wiki/Corrupt_Kelt)) it states that you are to obtain 15 succubi milk (or 10 and a pink egg), and max out his lust in combat. It says you must have a dick to turn Kelt into Kelly, and this will happen after you beat him. However I gathered in total 5 stacks succubi milk, because the way it was worded gave off a sense that you might have to use 5 stacks. No matter what I try I cannot seem to get corrupted Kelt, am I merely doing something wrong, or is the wiki just giving me false information?

**Comment by bonezinger** [comment]
I never had any problem turning Kelt into Kelly. In game, the option even hints that you "might need a lot of succubi milk"
When you go to Kelt, you're met with 3 options: Endure, Resist and Never, regarding how you want to deal with his asshole manner. You have to choose RESIST which, if you have enough succubi milk (3 stacks, total of 15), will prompt if you want to do it now or later. If you don't have enough, the game will hint at it.

What, exactly, are you doing that you're not managing it? And by exactly I mean like this:
1- Go to farm
2- Click Kelt
3- Click Resist

**Comment by CrimsonTheMad** [comment]
I have no clue why it wasn't working... I tried like, six times, having 5 stacks and it just wouldn't fuckin' work for a while. And then I go back into it and it suddenly works. Is it required to SPECIFICALLY resist? Or can I just fight him on my own time?

**Comment by Munkus11** [comment]
Hi. i have turned him twice now. 
You can turn him in your own time. It takes a positive truckload of succubi milk, since you have to do it several times. 
You need to have fifteen succubi milk in your inventory the first time and pick "Resist" (and you need a dick)
- There is a scene where you turn him and he is very upset about it. 

-> next time you go to farm, you notice that he has manged to turn himself BACK to male, but his dick is not quite as big as before. 

-> farm again succubi milk (easiest way is to collect them from the start and stack up when you see them for sale on a vendor and bomb all slots of your stash FULL of them + your inventory to make sure you have enough and maybe turn him on the day they are for sale in case you need more)
(->-> never worked with the egg for me though, i always needed the milk)

-> return back to Kelt, turn him once more. (15 succubi milk in inventory)
->-> he changes back AGAIN, but again has a smaller dick

-> return back to kelt, (10 more milk in inventory), change him once more

-> he FINALLY stays female and is Kelly

It takes a LOT of succubi milk and at least three times of you changing him. See it as a battle of will here. You have to be the more persistent one.
