### ISSUE TITLE
[CI] Versioned build dependencies

### ISSUE THREAD

**Issue by brrritssocold** [Kitteh6660/Corruption-of-Champions-Mod#1212]
Since updates from Apache and Adobe can break the build without warning, so #1211 happens repeatedly.

## Ideas:
- Add build dependencies to a separate repository and do controlled updates
- ?

**Comment by Stadler76** [comment]
Like I said in #1211, this time SF.net is to be blamed. I guess, if everything runs smoothly there again the build would stop failing.

@brrritssocold wrote:
> ## Ideas:
> - Add build dependencies to a separate repository and do controlled updates

That would be my first idea too that comes to my mind. Actually they could even be long outdated because its not mandatory for Travis to have up to date build deps I'd say.
