### ISSUE TITLE
Test is off screen

### ISSUE THREAD

**Issue by Agentluke18** [Kitteh6660/Corruption-of-Champions-Mod#1273]
I need help with sorting out text issue[Bug]

### I have checked the following before submitting this issue:

- [x ] The bug is still present in the latest release
- [x ] Searched the existing issues so I do not open a duplicate issue
- [x ] Filled out the template, so developers are less likely to ask for more info

### Overview
what should happen is all of the text should be able to be seen without issue, instead the text goes into the black bars....
	
### Game version
1.4.13b
	
### Expected behavior
what should happen is all of the text should be able to be seen without issue, instead the text goes into the black bars....
	
### Actual behavior
instead the text goes into the black bars....

### How often can this be reproduced?
probably instantly, by loading the game in internet explorer

### Steps to reproduce the issue
just load the bloody game

**Comment by Fusion-tech** [comment]
@Agentluke18  Can you append the title with the [Bug] prefix so the team knows it's a bug? Thank you!

I am having a similar issue, appending issue with my own notes.

### I have checked the following before submitting this issue:
- [X] The bug is still present in the latest release
- [X] Searched the existing issues so I do not open a duplicate issue
- [X] Filled out the template, so developers are less likely to ask for more info

### Overview
During a hostile encounter, text goes behind new enemy stats side-panel and is not readable. After encounter is finished, all text adjusts to new wider "window" and has to be highlighted in order to be readable.
	
### Game version
1.0.2_mod_1.4.13b
	
### Expected behaviour
Text should still be readable after encounter is finished and enemy stats side-panel is no longer displaying.
	
### Actual behaviour
Bug seems to be triggered by any hostile encounter with a mid-to-lengthy description. (Goblin was where bug first showed up.) Afterwards, all encounters were affected, even ones without images. The main camp description also is affected. Bug does not occur at all if enemy stats side-panel is disabled before playing.

### How often can this be reproduced?
Every time played so far

### Steps to reproduce the issue

Encounter hostile enemy and complete encounter. (Mine happened on my first goblin encounter.)

I am including an attachment with screenshots and a brand new save file where the issue has occurred

[Bug_Reports.zip](https://github.com/Kitteh6660/Corruption-of-Champions-Mod/files/1812061/Bug_Reports.zip)

_If possible, attach a save file that reproduces the issue._
_Please be aware that any files uploaded here are publicly accessible and cannot be deleted (however, the link to them can be removed)._

**Comment by thequestion1990** [comment]
I found that this is a bug caused by the new enemy status bar. you can disable it in the interface options. That new bar doesn't play well with the text or custom images.
