### ISSUE TITLE
you broke a deadly sin of gaming

### ISSUE THREAD

**Issue by synaris** [Kitteh6660/Corruption-of-Champions-Mod#1475]
you NEVER remove content you either fix it or leave it the fuck alone. NO ONE wants to play several versions of the same game in order to enjoy all the content it has to offer. seriously, do YOU have several versions of several games and see no problem switching between them to see everything? and this is how you end it? by sabatoging the mod? why? you hate the people that played it that much?  jojo and the behemoth removed for the hell of it? why is every coder so damn evil? do you get off on this? or do you look up to bethesda's business model that much?

i was going to play through this again, but you killed all my motivation.

**Comment by Kitteh6660** [comment]
It's not your fault. Blame the mod haters.

They were removed because the writing isn't up to par. Most of the removed
content can be found in the Beta Zone, a secret area.

Pure Jojo scenes felt unfitting and that was why I removed that. Sorry.

**Comment by synaris** [comment]
"felt unfitting" is the worst excuse i've ever heard. you could have had them optional, you could have made another swf file with them removed, and let people choose. you could have expanded the volcanic crag instead of nuking it, adding more things to it. but you kept making the wrong choices based on feelings??? i have no words. with an entire AAA industry making the same mistakes you made, i thought the average joe gamer would know better.

**Comment by Kitteh6660** [comment]
You do know how ambitious it is? I made too many unrealistic goals. I do not like copy-pasting content from Glacial Rift to Volcanic Crag and call it a new content, it doesn't feel right.

And as I said, they're not entirely removed. Just visit the Beta Zone after getting 60% of the achievements, beating the main story, and having turned on Debug Mode. From there, you can visit the unfinished and removed content.

You could play the /hgg/ version if you're so inclined, it's a fork off my mod.

**Comment by synaris** [comment]
a "beta zone" is immersion breaking. .and does this hgg version have all your content as well? i already made my stance on playing ten million versions clear. 

and the glacial rift and volcanic crag were FINE. just needed a few more characters/things to do. nuking them is the opposite of what should have been done.

also debug mode shouldnt be needed for content that worked fine.

**Comment by saintmichael95** [comment]
Yo, synaris you need to chill out. I partially agree with what you're saying, but you are being far too aggressive. Think about what you're saying. You literally called kitteh _evil_ because they removed some content... Do you see the ridiculousness of that? You're free to disagree with their decisions, but creating an account for the sole purpose of coming on here to rant and rave like a lunatic is not okay. I think YOU owe an apology.

That being said, I don't agree with removing the Volcanic Craig or Glacial Rift, though I do agree with removing Behemoth, as his writing was really subpar and not up to the standards of the rest of the game.

**Comment by synaris** [comment]
nope. not apologizing to an indian giver. 

and i said EVERY coder. this is a fine example of why i said every coder. https://tvtropes.org/pmwiki/pmwiki.php/Main/TheComputerIsACheatingBastard

removing content players enjoy aka "streamlining" is a huge problem plaguing the industry. elder scrolls alone is a great example, spells gaining damage with levels? removed in morrowind. levitation and the entire mysticism skill? removed in oblivion. stats and classes? removed in skyrim.

as i said before, someone subject to this treatment should know better. removing parts of a game, makes an objectively worse game. expecially the optional stuff. i made an account to bitch due toall of the knives i had to take out of my back. i held higher standards for indie devs of any kind, but i was wrong to do so as proven here.

**Comment by Ricz1990** [comment]
I never thought I would see a Karen in gaming. (LOL)

Do you know there are a lot of cut content in every single game and not just because streamlining, but because entagled codes and mechanisms or just game breaking parts? (Also, due to console gaming is a giant market, you have to make it playable for controller-friendly too (so UI is gonna change for sure), and port a game to another machine, system is a great job in volume. Not everyone can achieve to do so, e.g. Saints Row 3 on PC is a resource gobbler and we didn't yet talked about Arkham Knight which was recalled one and offered for a refund too due they couldn't make it work on PC well enough.)

But if you want good examples for that, get Daggerfall. Languages that can be learnt? Not in Morrowind. Because Daggerfall is basically an "ultimate fantasy life simulator", a huge ass project on it's own, barely made in time, rushed in the very end. (Also, basically you are talking about Bethesda, who couldn't learn the Havok Physics Engine since the rushed publishing of Morrowind. And ever since they are going by deadlines, that has to be met, and always publishing a game that is barely working.) 

But get back to base problem: these are mechanics and systems, not written content, that has been cut during the development phase. **And you are bitchin' about a written content, not even a mechanic or gameplay element, but a story content that is nothing special, and being cut every time in every game.** Cut the crap already.

Also, a huge lol for the URL about cheating game mechanics. Bro, do you even retro gaming? A lot of games scaled up the difficulty exponentially with these just to elongate the game. Ghosts and Goblins, Gods, Heart of Darkness... A lot of them did that in various ways, and nothing is unbeatable.

**Comment by Turkroach** [comment]
This nigga horny af

**Comment by saintmichael95** [comment]
> I never thought I would see a Karen in gaming. (LOL)

This entire comment, but especially this part, is so unbelievably accurate that I have no words. lol Perfect way to describe this dude.

**Comment by synaris** [comment]
"you get the industry you deserve". that statement is hitting home now. im a karen because your all masochists that enjoy being treated like garbage? you're all insane. and yes i retro game. practically nothing but retro game because people like kitteh are common as dirt in the modern industry. 

when you remove part of a game, you have an objectively worse game. a concept so simple even a child could understand it. if your fine with this just imagine it elsewhere.

imagine geno's origins removed from super mario RPG. "its just story"

imagine all romance options and all but one ending removed from dragon age origins. "its just story"

imagine the cutscenes removed from ninja gaiden. "its just story."

i don't know what its like to NOT have a brain and not compare things, so i have no idea how to communicate this concept to you idiots. its as obvious as the sky is blue. but i bet you disagree with me on that too.

**Comment by Ricz1990** [comment]
_"i don't know what its like to NOT have a brain"_

We do. A lifeform is trying to argue with us on a moral stand ground with his pinky finger held out like a snob aristocrat sipping tea. And by that attitude, you won't get anywhere, nor will be heard due to how you treat other by your impulsive behavour. And when you start with that, you hang the bell yourself in your neck to shake it furiously begging for a sheep-shearing.

_"imagine all romance options and all but one ending removed from dragon age origins. "its just story""_

Erm, Gothic and Risen was too just a story, and a good story with great atmosphere despite these didn't had nor needed romance options. Nor Diablo.

_"imagine the cutscenes removed from ninja gaiden. "its just story.""_

if you remove it, you get the original Duke Nukem platformer with ninja setting.

"imagine geno's origins removed from super mario RPG. "its just story""

If you cut it out, you get the hints and free space to create theories. Which would be happening due to you've got invested in the game and immersed well enough to care about it. Either way, does not make a huge difference.

So if you are saying that "you are retro gaming", then you should know these. Just as about how much ripoffs and clones and look-alikes were back in those days.

_"**when you remove part of a game, you have an objectively worse game. a concept so simple even a child could understand it. if your fine with this just imagine it elsewhere.**_

No, because that's the "more the merrier" principle. You don't get worse game with removed parts.
- Wolfenstein 3-D would have iterate it's original game's stealth, but the guys at id felt it's way more fun to just run and gun.
- Fallout 4 for instance had a deep sea quest, but got scrapped because a key element couldn't make it work. And I'm talking about the giant squid, which's assets are still in the game.
- Also a lot of quests (both TES and FO) got scrapped due to collisions with other quests, requirements or just poorly executed.
- Don't forget Gothic 2, which added multiple endings (yeah!), but had no real effects on the story: it's ended still in the same way (boo!).
- There are also lots of visual novels that are kinetic novels, which means there are no choices. Yet, they are a great stories that has actual characters, mood, atmosphere, setting.

On the other hand:
- The Talos Principle is a good game, but an awfully elongated one that does nothing to keep your attention well enough. Comparing it to The Turing Test, which keeps you entitled and always on track on the events and the mystery without long pauses between "maybe you'll discover the next story crumb".
- The same can be said with Persona 3, Sword Art Online: Fatal Bullet, Black Rock Shooter: The Game which are becoming enervated due to the grindfest you have to deal with. For mats, ammo, XP, skill points, weapons, accessories... you name it.

All in all: you don't need more to be better. Also, objectively is a loose term, because true objectivity does not exist. What we call objectivity is a bunch of people's subjective stand points all together. But what make's it "objectively" is if you believe so or you consider yourself convinced by them. What you called "an objective stand point" is just some hoarder bullshit.

Oh, and just to remind you, even Arthur C. Clarke rewrote some parts of his novels. Space Odyssey and Childhood's End for instances, due to "creator's discontent". Which is a common thing if you create something as well and you have a standard.

And here you are, dragging your ass through the carpet for something that not one, not two, but more people considered as an expendable loss due to how it was.

**Comment by synaris** [comment]
alright then. no convincing a blind fanboy like you. i've certainly never heard such inane justification before. a stealth option in wolfenstein 3d would have been awesome. 2 ways to play one game. but it seems you will justify any decision any developer makes. i give up. i've been arguing a basic concrete principle. when something is broke, you do not throw it out, you fix it. a cracked car windshield is replaced not removed. a wall of your house with a hole in it, is patched up not removed. if a part of a game is not up to standards, you improve it until it is or replace it with something better, you don't just take content out and give people nothing. unless you want an inferior game of course.

the trim the fat approach you're advocating for has been the cancer killing the industry starting in the 2000s. and im PISSED because i fucking idolized people that did what kitteh did, coc has been the best western RPG i've ever played, western RPG's are all about what you can do and how you can affect the world itself. taking those options away leads to an inferior game. and no amount "this has happened before so that makes it alright" bullshit will change that.

i made an account because i expected this from the triple A industry, not from someone subject to that treatment that should know better. but as you made it clear, im wasting my time. you are all content with less. standards be damned.

**Comment by saintmichael95** [comment]
You have clearly never tried developing a game. I have. It's not fucking easy. You have probably also never tried writing something. I do, all the time. I have lost count of all the times I have gotten through writing a five to eight thousand word chapter and then cut it out, not because it was bad writing, but because it didn't add anything to the story. But it's useless arguing with someone like you. People like you refuse to listen to reason, refuse to even attempt to see it from the other side's point of view. Before you throw shade at someone else, try walking a mile in their shoes you entitled piece of shit. People like you are the reason the gaming community has such a bad reputation.
