### ISSUE TITLE
Inexplicable Minotaur rape scene

### ISSUE THREAD

**Issue by Alceris** [Kitteh6660/Corruption-of-Champions-Mod#184]
The bull-man roughly grabs your hair and repositions himself to press against your asshole, slowly building the pressure until suddenly, the flared head pops into you.  **You have lost your anal virginity.**

This scene just kind of abruptly happened randomly when I went to the mountain. Nothing led up to this, I just clicked Mountain, and then a Minotaur materialized out of nothing with his hand in my hair and cock up my ass.

**Comment by Alceris** [comment]
Oh, I didn't realize someone already mentioned this. Whoops.

**Comment by LupusMaximus** [comment]
This is caused by rand(4) selecting chooser==1, the gangbang random not occurring, and not hitting rand(5) == 0 with a level >=10 or simply being less than level 10.

https://github.com/Kitteh6660/Corruption-of-Champions-Mod/blob/master/classes/classes/Scenes/Areas/Mountain.as#L203

Technically, not a bug, but it's completely unexplained and should probably be removed in favor of a "nothing happens and you left" event.

**Comment by Kitteh6660** [comment]
Resolved in 1.3.15.

In addition, the minotaur lord is intended to be encounterable at level 10+.
