### ISSUE TITLE
Unable to make imp statues

### ISSUE THREAD

**Issue by Dehje** [Kitteh6660/Corruption-of-Champions-Mod#402]
Was wondering how it works. I have the basilisk eye type, i can stare at the imps until it shows a blue (0), but all i can do is keep fighting, kill them or a skull, or have sex with them. How is it i make imp statues?

**Comment by Stadler76** [comment]
I've decided, that you can't put them into your inventory to add them to your camps wall later.

Hence, you have to complete your camp wall first (gate not required), before you can start petrifying and adding them to it.

**Comment by Dehje** [comment]
my wall is complete, even has 18 imp skulls on it, show those bastard imps what for

**Comment by Stadler76** [comment]
mmh, I've bumped the requirements to gain them a few days, before the snapshot was released.
Do you have a Bassy Womb? And how many eggs did you lay and how many eggs did Benoite lay?

**Comment by Dehje** [comment]
me, none, and with bassy i think like....near 50 or 60

**Comment by Stadler76** [comment]
The old requirement was:
- At least 12 eggs produced by you and/or Benoite in total

The new requirements are:
- You have the Basilisk Womb Perk
- You have layed at least 8 eggs by yourself (with the Basilisk Womb)
- You and/or Benoite have produced at least 15 eggs in total.

PS: Your answer is confusing: Do you have a Basilisk Womb and used it to lay the eggs or did you feminize Benoit and pregged her through the Sex option only?

Just look at your stats page, it should display something, like:
Benoit Eggs Laid: 166 <--- Laid by you with a bassy womb (Suggest option in Benoit(e)'s shop)
Benoite Eggs Produced: 7 <--- Laid by Benoite through 'Sex' option.

PS: Could you export your save, zip the file and attach it here, so I could check it?

**Comment by Dehje** [comment]
i think you just showed me the issue, my character does not have the basilisk womb bit since i always do my best to keep this one male

**Comment by Kitteh6660** [comment]
I might revert the requirement to old.

**Comment by Stadler76** [comment]
Well, the drawback is, that you have to grow a clit (e. g. with purified succi milk) to gain a bassy womb and lay enough eggs with it until you meet the updated requirements.
After that you can use Blue eggs until you've lost the clit again and Reduce your breasts to flats again with Reducto (e. g. bought from Rathazul) in order to become pure male again. The Womb won't go away, but it won't be usable, if you don't have a clit anymore.

Note, that if you've met those requirements once, there won't be any other requirements to gain them again and again. You could even turn pure male or genderless and turn back to a full human and still be able to gain the eyes from Benoit(e) to use stare and petrify imps.

Well, you decide, but maybe you wanna ask the community first?

**Comment by Stadler76** [comment]
@Kitteh6660:
How about the following requirement-update:
```diff
diff --git a/classes/classes/Scenes/Places/Bazaar/Benoit.as b/classes/classes/Scenes/Places/Bazaar/Benoit.as
index 0a8cb408..1dbc0449 100644
--- a/classes/classes/Scenes/Places/Bazaar/Benoit.as
+++ b/classes/classes/Scenes/Places/Bazaar/Benoit.as
@@ -172,16 +172,12 @@ public function benoitOffspring():int
 
 public function benoitBigFamily():Boolean
 {
-	// You need a bassy womb, ...
-	if (player.findPerk(PerkLib.BasiliskWomb) < 0)
-		return false;
+	// Either you've produced at least 25 eggs in total (You and/or Benoite)
+	if (benoitOffspring() >= 25)
+		return true;
 
-	// ... have laid at least 8 eggs by yourself ...
-	if (flags[kFLAGS.BENOIT_EGGS] < 8)
-		return false;
-
-	// ... and at least 15 eggs produced in total (You and/or Benoite)
-	return benoitOffspring() >= 15;
+	// ... or laid at least 12 eggs personally (with your bassy womb)
+	return flags[kFLAGS.BENOIT_EGGS] >= 12;
 }
 
 public function setBenoitShop(setButtonOnly:Boolean = false):void {
```

So pure males have to knock up Benoite a few times more, but the requirements v3 won't require a Bassy Womb or becoming female or herm anymore.

Still, its up to you, what 'version' you choose and feel free to play around with the numbers. The numbers in that diff are merely a suggestion.

**Comment by Stadler76** [comment]
mmh, since I'm considering to add a new basilisk transformative (probably obtained from Benoit(e) after or upon gaining bassy eyes) it would even make more sense to change this to allow pure males to gain bassy eyes (See the diff I've posted above).

Actually the bassy transformative would be an ingredient to create a cockatice TF item, if they're ever added to the game.
