### ISSUE TITLE
Giacomo offer cure for worms, but i'm not infested

### ISSUE THREAD

**Issue by DullDanger** [Kitteh6660/Corruption-of-Champions-Mod#461]
CoC_1.0.2_mod_1.4.swf
[Giacomo_worms.zip](https://github.com/Kitteh6660/Corruption-of-Champions-Mod/files/910403/Giacomo_worms.zip)

**Comment by Foxwells** [comment]
Just adding in that this is happening to me as well, gender and worms enabled/disabled doesn't seem to matter. Giacomo just offers it up. Jojo makes no mention of the worms, though, so it's definitely not that the game thinks I'm infested anyway...

After looking at the code, it seems to offer even if you aren't infested because of [this](https://github.com/Kitteh6660/Corruption-of-Champions-Mod/blob/master/classes/classes/Scenes/Explore/Giacomo.as#L76):

> player.hasStatusEffect(StatusEffects.Infested) >= 0

Greater than or equal to, meaning even if you aren't infested. Rip x:

**Comment by Stadler76** [comment]
Another bug introduced from PR #452 

Mostly effects commented out code, but that should fix all broken checks for `player.hasStatusEffect`
[20170411_0215_hasStatusEffect-fixes.diff.txt](https://github.com/Kitteh6660/Corruption-of-Champions-Mod/files/911780/20170411_0215_hasStatusEffect-fixes.diff.txt)

Grep-command used to find them:
```
grep -P --color=auto -rn "player.hasStatusEffect\([^)]+\)\s*[<>=]=?\s*0" .
```
