### ISSUE TITLE
Game not running.

### ISSUE THREAD

**Issue by jeromy384** [Kitteh6660/Corruption-of-Champions-Mod#625]
Hi, I recently tried to run the game, but I really don't understand how to really open the game at all. I do believe I've messed up the files somewhere, so I'll be posting pictures with it. I've been unsure what to load, what to run, and most of these files just say that it lacks a XML appearance or something and shows the document tree in Mozilla Firefox. I'm really unsure what to do and would really like help.
![example 2](https://cloud.githubusercontent.com/assets/28686379/26033690/f540cf40-3875-11e7-9a52-024f9c105315.PNG)
![example 1](https://cloud.githubusercontent.com/assets/28686379/26033691/fa028992-3875-11e7-8ee9-ac644ca33730.PNG)

**Comment by brrritssocold** [comment]
You can find the releases [here](https://github.com/Kitteh6660/Corruption-of-Champions-Mod/releases) (swf file).

In order to run the game you must have a flash player installed.
- Going by your screenshots, you are using firefox - you will need to [install the flash player plugin](https://support.mozilla.org/en-US/kb/install-flash-plugin-view-videos-animations-games)
- Chrome has an integrated flash player
- There is a standalone [flash player](https://fpdownload.macromedia.com/pub/flashplayer/updaters/25/flashplayer_25_sa.exe) from adobe

Either double-click on the swf file or drag the swf file into the window of the browser / flash player.

**Comment by Foxwells** [comment]
I would suggest not playing in browser. It's very easy for it to break because of changed MIME data. A downloaded flash player is generally better.

**Comment by brrritssocold** [comment]
What is the status of this issue? If it is resolved, please close it.
The issue can be re-opened at a later date if the issue re-occurs.

If there is no response I will request the issue be closed.

**Comment by Stadler76** [comment]
Its invalid, since the OP tried to run the wrong file.

Well, closing due to lack of feedback.
