### ISSUE TITLE
Opening the game

### ISSUE THREAD

**Issue by jibbernibber** [Kitteh6660/Corruption-of-Champions-Mod#708]
### Overview
Game will not open
	
### Game version
	CoC 1.0.2_mod_1.4.6
	
I do not understand how to open the game. I have tried on chrome and on internet explorer but when I download the CoC_1.0.2_mod_1.4.6b.swf file on https://github.com/Kitteh6660/Corruption-of-Champions-Mod/releases I download it and then when I try to open it from my downloads folder it just asks for me to download it again. Hopefully someone will be able to help me
 
If possible, attach a save file that reproduces the issue.
Please be aware that any files uploaded here are publicly accessible and cannot be deleted (but the link to them can be removed).

**Comment by Darth-Cthoras** [comment]
Use the standalone Flash Player Projector (flashplayer_XX_sa.exe - XX is the version) from [url]https://www.adobe.com/support/flashplayer/debug_downloads.html[/url] rather than a browser.

**Comment by brrritssocold** [comment]
What is the status of this issue? If it is resolved, please close it.

**Comment by Darth-Cthoras** [comment]
Think it's safe to assume the issue's resolved, given lack of response in over three weeks. I'd have closed it myself a tenday back but I can't.

**Comment by Stadler76** [comment]
mmh, how bout adding an .md file with a brief explanation how to run the game locally with Flash Player Projector? Better, than explaining the same thing over and over again.

PS: ~closing~ as won't fix, since no-on can fix the browsers not allowing to directly run .swf-files. The recommended solution has been explained anyway.
