### ISSUE TITLE
Can't corrupt Kelt

### ISSUE THREAD

**Issue by purrsifer** [Kitteh6660/Corruption-of-Champions-Mod#709]
> CoC Revamp Mod v1.4.6b

I've been trying to corrupt Kelt into Kelly for the past several hours, only to never have that option come up. I've got the required number of Suc. Milks, and even a large Pink Egg, and there's no option to begin turning him into Kelly available.

I consider this a pretty bad bug. :( I like being able to corrupt Kelt; it's been one of my favorite things to do!

**Comment by TheWrongOtaku** [comment]
Is your submission level high with him? If it is thenot you cannot corrupt him until it goes down

**Comment by TheScopedOne** [comment]
I have 0% submission and I still cant do it, all requirements and everything, no option is showed.

I heard a rumor that its because you HAVE to choose to be a Male at the start of the game otherwise the option never gets shown, even if you start as a female and get a dick or if you start as a Herm, it wont show itself to you.

I started as a herm, got all the requirements and it doesn't show an option, even if you fight him and win by lust (which is one of the requirements btw) it still doesn't show it.

**Comment by brrritssocold** [comment]
Seems to work on 1.4.7

Did you press the "Resist" button?

1. Start game as herm
2. Find farm
4. Explore farm until Kelt is found
5. Added 10 Sucubus Milk and small pink egg to inventory (via debug menu)
6. Visit Kelt, choose "resist"
7. Get options to corrupt Kelt

That said i looked at the item check code and it looks odd. Will do some more testing.
