### ISSUE TITLE
Can't Load Game File!

### ISSUE THREAD

**Issue by WildKing51** [Kitteh6660/Corruption-of-Champions-Mod#723]
No matter what browser I try, whenever I save a game to file, I can't load it. The feature has worked for me before, now it's just not working. I'm using version 1.4.7. What happens is when I try to load a file, I get a blank screen and nothing else. I liked using the feature, it was convenient, easy and reliable. I hope this issue is fixed soon.

**Comment by TheWrongOtaku** [comment]
I have the same problem, but I just can't load slot 6

**Comment by brrritssocold** [comment]
Can you please perform the load with the [Flash debugger](https://www.adobe.com/support/flashplayer/debug_downloads.html)?

Does it give an error output? If so please post that.
Otherwise it will be very difficult to reproduce the issue.

The blank screen is a good indicator that there is a exception / crash, but the default player silently ignores them.

**Comment by TheWrongOtaku** [comment]
Is there a way to run that on android? I'm playing on my tablet using a sfw player and all those say they're for computers.

**Comment by brrritssocold** [comment]
I'm afraid android is out of my league.

**Comment by WildKing51** [comment]
It seems to work on debugger. It's web browsers that I can't load it on. It used to work before.

**Comment by TheWrongOtaku** [comment]
Have you tried using the new update yet? I did and it worked so it might for you as well.

**Comment by WildKing51** [comment]
It works again! Hooray!

**Comment by brrritssocold** [comment]
If your issue is resolved, could you please close the ticket? Thanks in advance.
