### ISSUE TITLE
Crash on level up for CoC revamp Android

### ISSUE THREAD

**Issue by NoLifeKing16** [Kitteh6660/Corruption-of-Champions-Mod#946]
As the title says the game runs fine until i level up.
At that point when i click next it just crashes.
i' m using this version: https://mega.nz/#!FaYVgJyD!pWCAtoUGt-zXuAj8T-3ONsEbtV8fxGfIdoyfE4rn4w4

i play on oneplus 3t

**Comment by Hexxah** [comment]
The issue is more to do with the apk than COC-revamp (since those aren't officially built by kitteh6660).
I tried that apk and it crashed on my phone too, try contacting the creator of the apk maybe he might be able to fix it. 
Alternatively my builds can be found here: [https://github.com/Hexxah/CoC-MOD-Android-Build/releases](url)
